name: FillInTheWall
version: '${project.version}'
main: com.articreep.fillinthewall.FillInTheWall
api-version: '1.20'
commands:
  fillinthewall:
    description: testing commands
    usage: /fillinthewall <spawn/custom>
    aliases: [hitw, holeinthewall, fitw]
  registerplayingfield:
    description: Used to create a playing field and register it to config
    usage: /registerplayingfield
  settingsmenu:
    description: Used to alter settings for multiplayer games
    usage: /settingsmenu
