name: HoleInTheWall
version: '${project.version}'
main: com.articreep.holeinthewall.HoleInTheWall
api-version: '1.20'
commands:
  holeinthewall:
    description: test
    usage: /holeinthewall <reload/abort>
    aliases: hitw
  registerplayingfield:
    description: Used to create a playing field and register it to config
    usage: /registerplayingfield
