name: Maven Build + Deploy to Server

on:
  push:
    branches: [ "release" ]

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: release
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - uses: arti-dev/nmsaction@v1
      with:
        rev: 1.21.4
    - name: Install nms into m2
      run: mkdir -p $HOME/.m2/repository && cp -a nms-build/.m2/repository/. $HOME/.m2/repository

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: SFTP upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{secrets.SFTP_HOST}}
        username: ${{secrets.SFTP_USER}}
        password: ${{secrets.SFTP_PASSWORD}}
        port: 2222
        uploads: |
          /home/runner/work/FillInTheWall/FillInTheWall/target/ => /plugins/
        ignore: |
          !FillInTheWall.jar